In [1]:
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [4]:
 a = np.zeros((2, 3, 4))

In [5]:
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [7]:
plt.imgshow(a)

AttributeError: module 'matplotlib.pyplot' has no attribute 'imgshow'