In [1]:
import numpy as np

In [11]:
# matrix addition
mat_1 = np.array([[1, 2], [2, 4]])
mat_2 = np.array(([3, 5], [5, 7]))
mat_add = mat_1 + mat_2
print(np.add(mat_1, mat_2))
print(mat_3)

[[ 4  7]
 [ 7 11]]
[[ 4  7]
 [ 7 11]]


In [7]:
# subtraction
mat_sub = mat_1 - mat_2
print(mat_sub)

[[-2 -3]
 [-3 -3]]


In [12]:
# multiplication
mat_mul = mat_1*mat_2
print(mat_mul)
print(np.multiply(mat_1, mat_2))

[[ 3 10]
 [10 28]]
[[ 3 10]
 [10 28]]


In [13]:
# divide
mat_div = mat_1/mat_2
print(mat_div)
print(np.divide(mat_1, mat_2))

[[0.33333333 0.4       ]
 [0.4        0.57142857]]
[[0.33333333 0.4       ]
 [0.4        0.57142857]]


In [16]:
# square root of a matrix
mat_sqrt = np.sqrt(mat_1)
print(mat_sqrt)

[[1.         1.41421356]
 [1.41421356 2.        ]]
