In [1]:
import numpy as np

In [2]:
# let's create a two dimensional array !
x = np.array([[1, 2, 3], [3, 4, 5], [7, 8, 9]])
print(x.shape)


(3, 3)


In [12]:
v = np.array([1, 2, 4])
print(v.shape)

(3,)


In [13]:
y = np.empty_like(x)
print(y.shape)
print(y)

(3, 3)
[[140588490361752 140588490361752               0]
 [              0 140587721120744 140587721120745]
 [140587721120745 140587721120764              80]]


In [18]:
# Add the vector v to each row of the matrix x with an explicit loop
for each in range(3):
    y[each,:] = x[each, :] + v 

In [16]:
print(y)

[[140588490361752 140588490361752               0]
 [              4               6               9]
 [140587721120745 140587721120764              80]]
