In [1]:
import numpy as np

In [19]:
# let's create a two dimensional array !
x = np.array([[1, 2, 3], [3, 4, 5], [7, 8, 9], [10, 11, 12]])
print(x.shape)


(4, 3)


In [20]:
v = np.array([1, 2, 4])
print(v.shape)

(3,)


In [21]:
y = np.empty_like(x)
print(y.shape)
print(y)

(4, 3)
[[140588490361784  94091334502624 140588451828624]
 [140588451765920               0              65]
 [ 94091334502672  94091336124256               0]
 [              0               0               0]]


In [22]:
# Add the vector v to each row of the matrix x with an explicit loop
for each in range(4):
    y[each,:] = x[each, :] + v 

In [23]:
print(y)

[[ 2  4  7]
 [ 4  6  9]
 [ 8 10 13]
 [11 13 16]]
