In [2]:
import numpy as np

In [21]:
arr = np.array([[1, 2, 4, 5], [1, 2, 5, 2], [5, 2, 4, 7], [5, 2, 4, 7]])

In [22]:
print(arr)

[[1 2 4 5]
 [1 2 5 2]
 [5 2 4 7]
 [5 2 4 7]]


In [23]:
print(type(arr))

<class 'numpy.ndarray'>


In [17]:
print(arr.shape)

(3, 4)


In [26]:
print(arr[1][0], arr[2][1], arr[3][0])

1 2 5


In [39]:
# zero matrics
zero = np.zeros((2,2))
print(zero)

[[0. 0.]
 [0. 0.]]


In [40]:
# unity matrics 
one = np.ones((3, 3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
# full matrix
full = np.full((3, 3), 5)
print(full)

In [37]:
# identity matrix
identity = np.eye((3))
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
